name: Express Testing

on: [push]

jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello world"

            # Check out a copy of the repo's code so we can use it in this automation workflow
            - name: Checkout
              uses: actions/checkout@v4.2.1

            # Setup NodeJS so we can start doing NodeJS things
            - name: Setup Node.js environment
              uses: actions/setup-node@v4.0.4
              with:
                  node-version: 'latest'

            # Install NPM packages such as Express
            - name: Install dependencies for our project
              run: npm install

            # Run our project's `test` command to actually run the tests
            - name: Actually run the tests, finally!
              run: npm run test
